/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Company } from "../../company/base/Company";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumDataRequestUserRequestStatus } from "./EnumDataRequestUserRequestStatus";
import { EnumDataRequestUserStatusOptionSet } from "./EnumDataRequestUserStatusOptionSet";

@ObjectType()
class DataRequestUser {
  @ApiProperty({
    required: false,
    type: () => [Company],
  })
  @ValidateNested()
  @Type(() => Company)
  @IsOptional()
  company?: Array<Company>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  companyLookup!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  companyRelation!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdDateTime!: Date | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  requestCreatedAt!: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumDataRequestUserRequestStatus,
  })
  @IsEnum(EnumDataRequestUserRequestStatus)
  @IsOptional()
  @Field(() => EnumDataRequestUserRequestStatus, {
    nullable: true,
  })
  requestStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumDataRequestUserStatusOptionSet,
  })
  @IsEnum(EnumDataRequestUserStatusOptionSet)
  @IsOptional()
  @Field(() => EnumDataRequestUserStatusOptionSet, {
    nullable: true,
  })
  statusOptionSet?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  userLookup!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  userRelation!: string | null;
}

export { DataRequestUser as DataRequestUser };
