/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompanyUpdateManyWithoutDataRequestUsersInput } from "./CompanyUpdateManyWithoutDataRequestUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumDataRequestUserRequestStatus } from "./EnumDataRequestUserRequestStatus";
import { EnumDataRequestUserStatusOptionSet } from "./EnumDataRequestUserStatusOptionSet";

@InputType()
class DataRequestUserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CompanyUpdateManyWithoutDataRequestUsersInput,
  })
  @ValidateNested()
  @Type(() => CompanyUpdateManyWithoutDataRequestUsersInput)
  @IsOptional()
  @Field(() => CompanyUpdateManyWithoutDataRequestUsersInput, {
    nullable: true,
  })
  company?: CompanyUpdateManyWithoutDataRequestUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  companyLookup?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  companyRelation?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  createdDateTime?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  requestCreatedAt?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumDataRequestUserRequestStatus,
  })
  @IsEnum(EnumDataRequestUserRequestStatus)
  @IsOptional()
  @Field(() => EnumDataRequestUserRequestStatus, {
    nullable: true,
  })
  requestStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumDataRequestUserStatusOptionSet,
  })
  @IsEnum(EnumDataRequestUserStatusOptionSet)
  @IsOptional()
  @Field(() => EnumDataRequestUserStatusOptionSet, {
    nullable: true,
  })
  statusOptionSet?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  userLookup?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  userRelation?: string | null;
}

export { DataRequestUserUpdateInput as DataRequestUserUpdateInput };
