/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CompanyService } from "../company.service";
import { CompanyCreateInput } from "./CompanyCreateInput";
import { Company } from "./Company";
import { CompanyFindManyArgs } from "./CompanyFindManyArgs";
import { CompanyWhereUniqueInput } from "./CompanyWhereUniqueInput";
import { CompanyUpdateInput } from "./CompanyUpdateInput";
import { DataRequestFindManyArgs } from "../../dataRequest/base/DataRequestFindManyArgs";
import { DataRequest } from "../../dataRequest/base/DataRequest";
import { DataRequestWhereUniqueInput } from "../../dataRequest/base/DataRequestWhereUniqueInput";
import { DataRequestUserFindManyArgs } from "../../dataRequestUser/base/DataRequestUserFindManyArgs";
import { DataRequestUser } from "../../dataRequestUser/base/DataRequestUser";
import { DataRequestUserWhereUniqueInput } from "../../dataRequestUser/base/DataRequestUserWhereUniqueInput";

export class CompanyControllerBase {
  constructor(protected readonly service: CompanyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Company })
  async createCompany(
    @common.Body() data: CompanyCreateInput
  ): Promise<Company> {
    return await this.service.createCompany({
      data: data,
      select: {
        address: true,
        createdAt: true,
        email: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Company] })
  @ApiNestedQuery(CompanyFindManyArgs)
  async companies(@common.Req() request: Request): Promise<Company[]> {
    const args = plainToClass(CompanyFindManyArgs, request.query);
    return this.service.companies({
      ...args,
      select: {
        address: true,
        createdAt: true,
        email: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Company })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async company(
    @common.Param() params: CompanyWhereUniqueInput
  ): Promise<Company | null> {
    const result = await this.service.company({
      where: params,
      select: {
        address: true,
        createdAt: true,
        email: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Company })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCompany(
    @common.Param() params: CompanyWhereUniqueInput,
    @common.Body() data: CompanyUpdateInput
  ): Promise<Company | null> {
    try {
      return await this.service.updateCompany({
        where: params,
        data: data,
        select: {
          address: true,
          createdAt: true,
          email: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Company })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCompany(
    @common.Param() params: CompanyWhereUniqueInput
  ): Promise<Company | null> {
    try {
      return await this.service.deleteCompany({
        where: params,
        select: {
          address: true,
          createdAt: true,
          email: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/dataRequests")
  @ApiNestedQuery(DataRequestFindManyArgs)
  async findDataRequests(
    @common.Req() request: Request,
    @common.Param() params: CompanyWhereUniqueInput
  ): Promise<DataRequest[]> {
    const query = plainToClass(DataRequestFindManyArgs, request.query);
    const results = await this.service.findDataRequests(params.id, {
      ...query,
      select: {
        company: {
          select: {
            id: true,
          },
        },

        companyRelation: true,
        createdAt: true,
        id: true,
        requestCreatedAt: true,
        requestStatus: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userRelation: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dataRequests")
  async connectDataRequests(
    @common.Param() params: CompanyWhereUniqueInput,
    @common.Body() body: DataRequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataRequests: {
        connect: body,
      },
    };
    await this.service.updateCompany({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dataRequests")
  async updateDataRequests(
    @common.Param() params: CompanyWhereUniqueInput,
    @common.Body() body: DataRequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataRequests: {
        set: body,
      },
    };
    await this.service.updateCompany({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dataRequests")
  async disconnectDataRequests(
    @common.Param() params: CompanyWhereUniqueInput,
    @common.Body() body: DataRequestWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataRequests: {
        disconnect: body,
      },
    };
    await this.service.updateCompany({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/dataRequestUsers")
  @ApiNestedQuery(DataRequestUserFindManyArgs)
  async findDataRequestUsers(
    @common.Req() request: Request,
    @common.Param() params: CompanyWhereUniqueInput
  ): Promise<DataRequestUser[]> {
    const query = plainToClass(DataRequestUserFindManyArgs, request.query);
    const results = await this.service.findDataRequestUsers(params.id, {
      ...query,
      select: {
        companyLookup: true,
        companyRelation: true,
        createdAt: true,
        createdDateTime: true,
        id: true,
        requestCreatedAt: true,
        requestStatus: true,
        statusOptionSet: true,
        updatedAt: true,
        userLookup: true,
        userRelation: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dataRequestUsers")
  async connectDataRequestUsers(
    @common.Param() params: CompanyWhereUniqueInput,
    @common.Body() body: DataRequestUserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataRequestUsers: {
        connect: body,
      },
    };
    await this.service.updateCompany({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dataRequestUsers")
  async updateDataRequestUsers(
    @common.Param() params: CompanyWhereUniqueInput,
    @common.Body() body: DataRequestUserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataRequestUsers: {
        set: body,
      },
    };
    await this.service.updateCompany({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dataRequestUsers")
  async disconnectDataRequestUsers(
    @common.Param() params: CompanyWhereUniqueInput,
    @common.Body() body: DataRequestUserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataRequestUsers: {
        disconnect: body,
      },
    };
    await this.service.updateCompany({
      where: params,
      data,
      select: { id: true },
    });
  }
}
